services:
  caldavcalendar:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3102:3000"

    environment:
      NODE_ENV: production
      URL: ${URL}
      CIS_USER: ${CIS_USER}
      CIS_PASSWORD: ${CIS_PASSWORD}

    restart: always
